### ISSUE TITLE
Ability to exit waiting queue.

### ISSUE THREAD

**Issue by dfletcher06** [Colemata/CIS457#1]
When the user enters a queue for a game, the user should have the ability to enter a command to exit the queue. Currently the message 'Still Waiting' will continue to repeat.

**Comment by Colemata** [comment]
This would require doing multiple threads while waiting for the queue to pop. Maybe instead we can set like a max wait timer and if no one else joins the queue in a certain amount of time we can remove the user after that time expires?

Just to make it easier?

**Comment by dfletcher06** [comment]
Yes, we could do that. My thought process was that if the user starts a game, then they have no ability to exit the queue.
